### DISCUSSION TITLE
Nonebot Plugin Alconna 0.51.0

### DISCUSSION THREAD

**Discussion by RF-Tar-Railt** [nonebot/plugin-alconna#65] [Announcements]
## 新增
* `FallbackStrategy.auto` 策略，会根据执行每个元素的情况执行最佳的回退策略
* `UniMessage` 的序列化&反序列化方法 `.load` 和 `.dump`，用于持久化消息
  * `dump` 将消息序列化为 JSON 格式；若不指定 media_save_dir，则会尝试导入 `nonebot_plugin_localstore` 并使用其提供的路径。
  否则，将会尝试使用当前工作目录。
  * `load 从 JSON 数据加载消息`
 * `command_from_json/yaml` 和 `commands_from_json/yaml` 函数，用于从 JSON/YAML 文件中加载 Command 对象：
 	```python
	from nonebot_plugin_alconna import command_from_yaml

    cmd = command_from_yaml("foo.yml").build(...)
	```
	foo.yml:
	```yml
	command: foo <bar:str>
	help: 测试
	usage: foo <bar>
	shortcuts:
	  - key: 测试
	    args: ["123"]
	actions:
	  -
	    params: ["bar"]
	    code: |
	      return f"hello, {bar}"
	```
* 内置插件 `with`，用于在当前群组场景内设置一个局部命令前缀。对于包含多个子命令的指令，该插件可以使得此指令进行更加便捷的调用：
		![image](https://github.com/user-attachments/assets/de60eefb-0cde-4c74-aecd-866214b4acf1)

## 改进
* `Text.color` 支持了更多的颜色
* `on_alconna` 中的配置项参数 (例如 `use_cmd_start`) 现在为 `bool | None` 类型：
  * 只有在类型为 None/ 不声明参数时，会跟随全局配置 

## 修复
* :bug: add type annotation for `image_fetch` by @lgc2333 in https://github.com/nonebot/plugin-alconna/pull/61
* :bug: version 0.50.3 by @RF-Tar-Railt in https://github.com/nonebot/plugin-alconna/pull/63

## New Contributors
* @RF-Tar-Railt made their first contribution in https://github.com/nonebot/plugin-alconna/pull/63

**Full Changelog**: https://github.com/nonebot/plugin-alconna/compare/v0.50.3...v0.51.0

<hr /><em>This discussion was created from the release <a href='https://github.com/nonebot/plugin-alconna/releases/tag/v0.51.0'>Nonebot Plugin Alconna 0.51.0</a>.</em>
